- docker-compose.yml
- src/main/resources/application.yml
<br/>
- #3 
<br/>
- 기능에서 어떤 부분이
- 구현되었는지 설명해주세요
postgre docker 연결
<br/>
<br/>
> :sparkles: feat: - application.yml에 postgre 연결 - docker-compose.yml에 postgre 설정

- src/main/java/com/example/cloudfour/peopleofdelivery/PeopleofdeliveryApplication.java
- src/main/java/com/example/cloudfour/peopleofdelivery/global/entity/BaseEntity.java
- BaseEntity 생성
- 실행파일 내 Audit 어노테이션 추가
<br/>
- [FEAT #11](https://github.com/goorm-engineers4/people_of_delivery/issues/11#issue-3261953478)
<br/>
- 로그 기록 BaseEntity 생성
- JPA Audit 추가
<br/>
<br/>
> ✨ feat: BaseEntity 생성

- src/main/java/com/example/cloudfour/peopleofdelivery/global/entity/BaseEntity.java
<br/>
- [[FEAT] 베이스 엔터티 생성 #11](https://github.com/goorm-engineers4/people_of_delivery/issues/11#issue-3261953478)
<br/>
- BaseEntity 내 Date -> LocalDateTime
- Temporal 삭제
- BaseEntity를 상속받는 자식 Entity는 @SuperBuilder 사용
<br/>
<br/>
> ✨ [FEAT] BaseEntity 수정

- src/main/java/com/example/cloudfour/peopleofdelivery/domain/cart/entity/Cart.java
- src/main/java/com/example/cloudfour/peopleofdelivery/domain/cartitem/entity/CartItem.java
- src/main/java/com/example/cloudfour/peopleofdelivery/domain/order/entity/Order.java
- src/main/java/com/example/cloudfour/peopleofdelivery/domain/order/entity/OrderHistory.java
- src/main/java/com/example/cloudfour/peopleofdelivery/domain/order/enums/OrderStatus.java
- src/main/java/com/example/cloudfour/peopleofdelivery/domain/order/enums/OrderType.java
- src/main/java/com/example/cloudfour/peopleofdelivery/domain/order/enums/ReceiptType.java
- src/main/java/com/example/cloudfour/peopleofdelivery/domain/orderitem/entity/OrderItem.java
- src/main/java/com/example/cloudfour/peopleofdelivery/domain/payment/entity/Payment.java
- src/main/java/com/example/cloudfour/peopleofdelivery/domain/payment/entity/PaymentHistory.java
- src/main/java/com/example/cloudfour/peopleofdelivery/domain/payment/enums/PaymentStatus.java
- src/main/java/com/example/cloudfour/peopleofdelivery/domain/region/entity/Region.java
- src/main/java/com/example/cloudfour/peopleofdelivery/domain/review/entity/Review.java
- src/main/java/com/example/cloudfour/peopleofdelivery/domain/user/entity/User.java
- src/main/java/com/example/cloudfour/peopleofdelivery/domain/user/enums/Role.java
- src/main/java/com/example/cloudfour/peopleofdelivery/domain/useraddress/entity/UserAddress.java
- src/main/java/com/example/cloudfour/peopleofdelivery/global/ai/entity/AiLog.java
- src/test/java/com/example/cloudfour/peopleofdelivery/domain/useraddress/entity/UserAddressTest.java
<br/>
- #12 
<br/>
- 기능에서 어떤 부분이
- 구현되었는지 설명해주세요
주요 엔티티 생성, 연관관계 등록
<br/>
메뉴, 메뉴 옵션 엔티티 아직 없어서 TODO로 남겨놈
가게 엔티티 없어서 TODO로 남겨놈
<br/>
> ✨ [FEAT] 주요 엔티티 생성

- .gitignore
- docker-compose.yml
<br/>
- #31 
<br/>
- docker-compose, gitignore 재업로드
<br/>
<br/>
> 📝 [DOCS] docker-compose, gitignore 재업로드

- src/main/java/com/example/cloudfour/peopleofdelivery/domain/review/controller/ReviewController.java
- src/main/java/com/example/cloudfour/peopleofdelivery/domain/review/converter/ReviewConverter.java
- src/main/java/com/example/cloudfour/peopleofdelivery/domain/review/dto/ReviewRequestDTO.java
- src/main/java/com/example/cloudfour/peopleofdelivery/domain/review/dto/ReviewResponseDTO.java
- src/main/java/com/example/cloudfour/peopleofdelivery/domain/review/entity/Review.java
- src/main/java/com/example/cloudfour/peopleofdelivery/domain/review/repository/ReviewRepository.java
- src/main/java/com/example/cloudfour/peopleofdelivery/domain/review/service/command/ReviewCommandService.java
- src/main/java/com/example/cloudfour/peopleofdelivery/domain/review/service/command/ReviewCommandServiceImpl.java
- src/main/java/com/example/cloudfour/peopleofdelivery/domain/review/service/query/ReviewQueryService.java
- src/main/java/com/example/cloudfour/peopleofdelivery/domain/review/service/query/ReviewQueryServiceImpl.java
<br/>
- #30 
<br/>
- 리뷰 MVC 완성
<br/>
현재 Spring Security 미완성으로 인해 임시로 @AuthenticationPrincipal 를 통해 현재 로그인 중인 사용자 정보를 가져왔습니다.
추후에 Spring Security 완성되면 커스텀 어노테이션 @AuthUser 사용할 예정입니다.
<br/>
> ✨ [FEAT] 리뷰 엔티티 MVC 완성

- src/main/java/com/example/cloudfour/peopleofdelivery/domain/cartitem/controller/CartItemController.java
- src/main/java/com/example/cloudfour/peopleofdelivery/domain/cartitem/converter/CartItemConverter.java
- src/main/java/com/example/cloudfour/peopleofdelivery/domain/cartitem/dto/CartItemRequestDTO.java
- src/main/java/com/example/cloudfour/peopleofdelivery/domain/cartitem/dto/CartItemResponseDTO.java
- src/main/java/com/example/cloudfour/peopleofdelivery/domain/cartitem/service/command/CartItemCommandService.java
- src/main/java/com/example/cloudfour/peopleofdelivery/domain/cartitem/service/query/CartItemQueryService.java
<br/>
- [Feat/#47 cart item](https://github.com/goorm-engineers4/people_of_delivery/issues/47)
<br/>
- 컨트롤러 구현
- 그외 껍데기 코드 구현
<br/>
<br/>
> ✨ [FEAT] 장바구니 아이템 관련 컨트롤러 구현

- src/main/java/com/example/cloudfour/peopleofdelivery/domain/region/entity/Region.java
- src/test/java/com/example/cloudfour/peopleofdelivery/domain/TestFixtureFactory.java
<br/>
<br/>
- Region 내 UserAddress 경로 수정
- TestFixtureFactory 내 orderitem 경로 수정
<br/>
<br/>
> 🔨 refactor : import 경로 수정

- src/main/java/com/example/cloudfour/peopleofdelivery/domain/user/exception/UserAddressErrorCode.java
- src/main/java/com/example/cloudfour/peopleofdelivery/domain/user/exception/UserAddressException.java
- src/main/java/com/example/cloudfour/peopleofdelivery/domain/user/repository/UserAddressRepository.java
<br/>
- [[FIX] 패키지 구조 수정 #63](https://github.com/goorm-engineers4/people_of_delivery/issues/63#issue-3278871995)
<br/>
- UserAddress repository -> User
- UserAddress exception -> User
<br/>
<br/>
> 🔨 fix : UserAddress 패키지 삭제

- src/main/java/com/example/cloudfour/peopleofdelivery/domain/cartitem/controller/CartItemController.java
- src/main/java/com/example/cloudfour/peopleofdelivery/domain/cartitem/converter/CartItemConverter.java
- src/main/java/com/example/cloudfour/peopleofdelivery/domain/cartitem/dto/CartItemRequestDTO.java
- src/main/java/com/example/cloudfour/peopleofdelivery/domain/cartitem/dto/CartItemResponseDTO.java
- src/main/java/com/example/cloudfour/peopleofdelivery/domain/cartitem/entity/CartItem.java
- src/main/java/com/example/cloudfour/peopleofdelivery/domain/cartitem/repository/CartItemRepository.java
- src/main/java/com/example/cloudfour/peopleofdelivery/domain/cartitem/service/command/CartItemCommandService.java
- src/main/java/com/example/cloudfour/peopleofdelivery/domain/cartitem/service/query/CartItemQueryService.java
<br/>
- [feat/#70-CartItem-new](https://github.com/goorm-engineers4/people_of_delivery/issues/70)
<br/>
- Controller 수정
- Converter 추가
- DTO 수정
- Entity Update 추가
- Repository 추가
- Service 추가
<br/>
<br/>
> ✨ [Feat] 장바구니아이템 구현

- src/main/java/com/example/cloudfour/peopleofdelivery/domain/review/controller/ReviewController.java
- src/main/java/com/example/cloudfour/peopleofdelivery/domain/review/converter/ReviewConverter.java
- src/main/java/com/example/cloudfour/peopleofdelivery/domain/review/dto/ReviewResponseDTO.java
- src/main/java/com/example/cloudfour/peopleofdelivery/domain/review/repository/ReviewRepository.java
- src/main/java/com/example/cloudfour/peopleofdelivery/domain/review/service/command/ReviewCommandServiceImpl.java
- src/main/java/com/example/cloudfour/peopleofdelivery/domain/review/service/query/ReviewQueryServiceImpl.java
<br/>
- #71 
<br/>
review 커서 페이지네이션 적용
<br/>
<br/>
> ✨ [FEAT] 리뷰 커서 페이지네이션 적용

- src/main/java/com/example/cloudfour/peopleofdelivery/domain/user/controller/UserController.java
- src/main/java/com/example/cloudfour/peopleofdelivery/global/auth/config/SecurityConfig.java
- src/main/java/com/example/cloudfour/peopleofdelivery/global/auth/jwt/JwtAuthenticationFilter.java
- src/main/java/com/example/cloudfour/peopleofdelivery/global/auth/jwt/JwtTokenProvider.java
- src/main/java/com/example/cloudfour/peopleofdelivery/global/auth/userdetails/CustomUserDetails.java
<br/>
- [✨ [FEAT] Security 설정 #59](https://github.com/goorm-engineers4/people_of_delivery/issues/59#issue-3275661250)
<br/>
- SecurityConfig 내 상세 설정 수정
- CustomUserDetail 생성
<br/>
<br/>
> ✨ [FEAT] Security 설정

- src/main/java/com/example/cloudfour/peopleofdelivery/domain/store/controller/StoreController.java
- src/main/java/com/example/cloudfour/peopleofdelivery/domain/store/converter/StoreConverter.java
- src/main/java/com/example/cloudfour/peopleofdelivery/domain/store/dto/StoreRequestDTO.java
- src/main/java/com/example/cloudfour/peopleofdelivery/domain/store/dto/StoreResponseDTO.java
- src/main/java/com/example/cloudfour/peopleofdelivery/domain/store/entity/Store.java
- src/main/java/com/example/cloudfour/peopleofdelivery/domain/store/repository/StoreRepository.java
- src/main/java/com/example/cloudfour/peopleofdelivery/domain/store/service/command/StoreCommandService.java
- src/main/java/com/example/cloudfour/peopleofdelivery/domain/store/service/query/StoreQueryService.java
- src/test/java/com/example/cloudfour/peopleofdelivery/domain/store/service/command/StoreCommandServiceTest.java
<br/>
- #36 
<br/>
- 가게 엔티티에 필요한 Repository, Service, DTO, Converter 구현
-  가게 엔티티 목록 조회에 커서 페이지네이션 적용
- 가게 생성, 삭제, 수정, (내)가게 조회, 전체가게 조회, 가게 상세조회, 카테고리별 가게조회
<br/>
<br/>
> ✨ [FEAT] 가게 엔티티 구현

- src/test/java/com/example/cloudfour/peopleofdelivery/fixtures/Factory.java
- src/test/java/com/example/cloudfour/peopleofdelivery/mock/TestFixtureFactory.java
- src/test/java/com/example/cloudfour/peopleofdelivery/unit/domain/menu/service/command/MenuCommandServiceImplTest.java
- src/test/java/com/example/cloudfour/peopleofdelivery/unit/domain/menu/service/query/MenuQueryServiceImplTest.java
- src/test/java/com/example/cloudfour/peopleofdelivery/unit/domain/store/service/command/StoreCommandServiceTest.java
<br/>
- [#90  ](https://github.com/goorm-engineers4/people_of_delivery/issues/90)
<br/>
- TestFixtureFactory 위치 변경
<br/>
<br/>
> 🔨[REFACTOR] 테스트 목데이터 위치 변경

- src/main/java/com/example/cloudfour/peopleofdelivery/domain/menu/controller/MenuController.java
- src/main/java/com/example/cloudfour/peopleofdelivery/domain/menu/converter/MenuConverter.java
- src/main/java/com/example/cloudfour/peopleofdelivery/domain/menu/dto/MenuRequestDTO.java
- src/main/java/com/example/cloudfour/peopleofdelivery/domain/menu/dto/MenuResponseDTO.java
- src/main/java/com/example/cloudfour/peopleofdelivery/domain/menu/entity/Menu.java
- src/main/java/com/example/cloudfour/peopleofdelivery/domain/menu/entity/MenuCategory.java
- src/main/java/com/example/cloudfour/peopleofdelivery/domain/menu/entity/MenuOption.java
- src/main/java/com/example/cloudfour/peopleofdelivery/domain/menu/repository/MenuCategoryRepository.java
- src/main/java/com/example/cloudfour/peopleofdelivery/domain/menu/repository/MenuOptionRepository.java
- src/main/java/com/example/cloudfour/peopleofdelivery/domain/menu/repository/MenuRepository.java
- src/main/java/com/example/cloudfour/peopleofdelivery/domain/menu/service/command/MenuCommandServiceImpl.java
- src/main/java/com/example/cloudfour/peopleofdelivery/domain/menu/service/query/MenuQueryServiceImpl.java
<br/>
- #94 
<br/>
- 와일드카드 import를 개별 import로 변경
- 코드 주석 제거
<br/>
<br/>
> 🔨 [REFACTOR] 메뉴 엔티티 import 문 정리 및 코드 주석 제거

- src/main/java/com/example/cloudfour/peopleofdelivery/domain/store/controller/StoreController.java
- src/main/java/com/example/cloudfour/peopleofdelivery/domain/store/converter/StoreConverter.java
- src/main/java/com/example/cloudfour/peopleofdelivery/domain/store/dto/StoreRequestDTO.java
- src/main/java/com/example/cloudfour/peopleofdelivery/domain/store/dto/StoreResponseDTO.java
- src/main/java/com/example/cloudfour/peopleofdelivery/domain/store/entity/Store.java
- src/main/java/com/example/cloudfour/peopleofdelivery/domain/store/entity/StoreCategory.java
- src/main/java/com/example/cloudfour/peopleofdelivery/domain/store/repository/StoreRepository.java
- src/main/java/com/example/cloudfour/peopleofdelivery/domain/store/service/command/StoreCommandService.java
- src/main/java/com/example/cloudfour/peopleofdelivery/domain/store/service/query/StoreQueryService.java
<br/>
- #92 
<br/>
- Store관련 코드들에서 모든 주석제거 및 import문에서 .*제거 후 구체적으로 수동 기입
<br/>
> 🔨 [REFACTOR] Store 엔티티 코드 주석제거 및 import문 .*제거

- src/test/java/com/example/cloudfour/peopleofdelivery/fixtures/Factory.java
<br/>
- #101 
<br/>
- user.getCarts().add(cart) -> cart.setUser(user)
- store.getCarts().add(cart) -> cart.setStore(store)
- orderhitory 부분 삭제
- 권한확인 메서드 추가 createMockUserWithRole
<br/>
<br/>
> 🐛 [FIX] Factory 코드 수정

- src/main/java/com/example/cloudfour/peopleofdelivery/domain/store/entity/Store.java
<br/>
- #99 
<br/>
- 동일한 가게명이 존재하면 안되기 때문에, Store의 name필드에 unique = true 조건 추가
<br/>
<br/>
> 🔨 [REFACTOR] : Store엔티티 name 필드 수정

- src/main/java/com/example/cloudfour/peopleofdelivery/domain/menu/converter/MenuOptionConverter.java
- src/main/java/com/example/cloudfour/peopleofdelivery/domain/menu/dto/MenuOptionResponseDTO.java
- src/main/java/com/example/cloudfour/peopleofdelivery/domain/order/controller/OrderController.java
- src/main/java/com/example/cloudfour/peopleofdelivery/domain/order/converter/OrderConverter.java
- src/main/java/com/example/cloudfour/peopleofdelivery/domain/order/converter/OrderItemConverter.java
- src/main/java/com/example/cloudfour/peopleofdelivery/domain/order/dto/OrderItemResponseDTO.java
- src/main/java/com/example/cloudfour/peopleofdelivery/domain/order/dto/OrderRequestDTO.java
- src/main/java/com/example/cloudfour/peopleofdelivery/domain/order/dto/OrderResponseDTO.java
- src/main/java/com/example/cloudfour/peopleofdelivery/domain/order/service/command/OrderCommandServiceImpl.java
- src/main/java/com/example/cloudfour/peopleofdelivery/domain/order/service/query/OrderQueryServiceImpl.java
<br/>
- #83 
<br/>
1. 주문 생성 requestdto에 쓸모없는 fk 삭제 3630f7e6d96d8379369b38627d3cb3e677a935fe
2. 주문 생성 알고리즘 변경, 추가 3f1992efa4b6b5e9f1d09be6953eb87574b4f7db
3. 주문 조회 DTO에 메뉴 옵션을 엔티티 그대로 사용함. 메뉴 옵션 DTO 사용하도록 변경 fde870bd1730dbec8af3a4cf86871730166ed674
<br/>
<br/>
> :sparkles: [FEAT] 주문 생성 기능 변경, 추가

- src/main/java/com/example/cloudfour/peopleofdelivery/domain/cart/controller/CartController.java
- src/main/java/com/example/cloudfour/peopleofdelivery/domain/cart/repository/CartRepository.java
- src/main/java/com/example/cloudfour/peopleofdelivery/domain/cart/service/command/CartCommandService.java
- src/main/java/com/example/cloudfour/peopleofdelivery/domain/cart/service/query/CartQueryService.java
- src/main/java/com/example/cloudfour/peopleofdelivery/domain/cartitem/controller/CartItemController.java
- src/main/java/com/example/cloudfour/peopleofdelivery/domain/cartitem/converter/CartItemConverter.java
- src/main/java/com/example/cloudfour/peopleofdelivery/domain/cartitem/dto/CartItemRequestDTO.java
- src/main/java/com/example/cloudfour/peopleofdelivery/domain/cartitem/dto/CartItemResponseDTO.java
- src/main/java/com/example/cloudfour/peopleofdelivery/domain/cartitem/entity/CartItem.java
- src/main/java/com/example/cloudfour/peopleofdelivery/domain/cartitem/repository/CartItemRepository.java
- src/main/java/com/example/cloudfour/peopleofdelivery/domain/cartitem/service/command/CartItemCommandService.java
- src/main/java/com/example/cloudfour/peopleofdelivery/domain/cartitem/service/query/CartItemQueryService.java
- src/main/java/com/example/cloudfour/peopleofdelivery/domain/menu/converter/MenuConverter.java
- src/main/java/com/example/cloudfour/peopleofdelivery/domain/menu/dto/MenuResponseDTO.java
- src/main/java/com/example/cloudfour/peopleofdelivery/domain/menu/service/query/MenuQueryServiceImpl.java
<br/>
- #110 
<br/>
장바구니, 장바구니 아이템 누락된 기능, 수정해야 하는 기능 개발 완료
<br/>
<br/>
> ✨ [FEAT] 장바구니,장바구니 아이템 기능 디벨롭

- src/main/java/com/example/cloudfour/peopleofdelivery/domain/menu/controller/MenuController.java
- src/main/java/com/example/cloudfour/peopleofdelivery/domain/menu/dto/MenuOptionResponseDTO.java
- src/main/java/com/example/cloudfour/peopleofdelivery/domain/menu/dto/MenuRequestDTO.java
- src/main/java/com/example/cloudfour/peopleofdelivery/domain/menu/dto/MenuResponseDTO.java
- src/main/java/com/example/cloudfour/peopleofdelivery/domain/menu/entity/Menu.java
- src/main/java/com/example/cloudfour/peopleofdelivery/domain/menu/entity/MenuCategory.java
- src/main/java/com/example/cloudfour/peopleofdelivery/domain/menu/entity/MenuOption.java
- src/main/java/com/example/cloudfour/peopleofdelivery/domain/menu/repository/MenuOptionRepository.java
- src/main/java/com/example/cloudfour/peopleofdelivery/domain/menu/repository/MenuRepository.java
- src/main/java/com/example/cloudfour/peopleofdelivery/domain/menu/service/command/MenuCommandServiceImpl.java
- src/main/java/com/example/cloudfour/peopleofdelivery/domain/menu/service/query/MenuQueryServiceImpl.java
- src/test/java/com/example/cloudfour/peopleofdelivery/unit/domain/menu/service/command/MenuCommandServiceImplTest.java
- src/test/java/com/example/cloudfour/peopleofdelivery/unit/domain/menu/service/query/MenuQueryServiceImplTest.java
<br/>
- #113 
<br/>
- MenuOption 엔티티 수정
- MenuOptionRepository 및 쿼리 메서드 구현
- MenuOption CRUD 서비스 로직 추가
- MenuOptionResponseDTO 및 요청 DTO 구현
- 메뉴 옵션 생성/수정/삭제/목록 조회/상세 조회 API 구현
- MASTER/OWNER 권한별 접근 제어 적용
<br/>
<br/>
> ✨ [FEAT] 메뉴 옵션 기능 추가

- src/main/java/com/example/cloudfour/peopleofdelivery/domain/menu/dto/MenuRequestDTO.java
- src/main/java/com/example/cloudfour/peopleofdelivery/domain/menu/entity/MenuCategory.java
- src/main/java/com/example/cloudfour/peopleofdelivery/domain/menu/service/command/MenuCommandServiceImpl.java
<br/>
- #117 
<br/>
메뉴 옵션 빌드 해결
<br/>
<br/>
> :bug: fix: 메뉴 옵션 빌드 오류 해결

- src/test/java/com/example/cloudfour/peopleofdelivery/fixtures/Factory.java
<br/>
- #121 
<br/>
- createMockUserWithRole 메서드를 실제 엔티티 객체 대신 완전한 Mock 객체를 생성하도록 수정
- ID가 올바르게 설정된 Mock User 객체를 생성하는 새로운 메서드들 추가
<br/>
<br/>
> 🐛 [FIX] 메뉴 테스트 실패 문제 해결(Factory 수정)

- src/main/java/com/example/cloudfour/peopleofdelivery/domain/user/repository/UserRepository.java
- src/main/java/com/example/cloudfour/peopleofdelivery/domain/user/service/UserService.java
- src/main/java/com/example/cloudfour/peopleofdelivery/global/auth/dto/TokenDto.java
- src/main/java/com/example/cloudfour/peopleofdelivery/global/auth/jwt/JwtAuthenticationFilter.java
- src/main/java/com/example/cloudfour/peopleofdelivery/global/auth/jwt/JwtTokenProvider.java
- src/main/java/com/example/cloudfour/peopleofdelivery/global/auth/oauth/CustomOAuth2UserService.java
- src/main/java/com/example/cloudfour/peopleofdelivery/global/auth/service/AuthService.java
- src/main/java/com/example/cloudfour/peopleofdelivery/global/auth/service/JpaUserDetailsService.java
- src/main/java/com/example/cloudfour/peopleofdelivery/global/auth/service/OAuthService.java
- userrepository isdeleted -> deleted로 변경
<br/>
- [[FIX] User softdelete 수정 #123 ](https://github.com/goorm-engineers4/people_of_delivery/issues/123#issue-3287951709)
<br/>
- userrepository isdeleted -> deleted 수정
- 관련 코드 isdeleted -> deleted 수정
<br/>
<br/>
> 🔨 Refactor : isdeleted 삭제

- src/test/java/com/example/cloudfour/peopleofdelivery/unit/domain/cartitem/repository/CartItemRepositoryTest.java
- src/test/java/com/example/cloudfour/peopleofdelivery/unit/domain/cartitem/service/command/CartItemCommandServiceTest.java
- src/test/java/com/example/cloudfour/peopleofdelivery/unit/domain/cartitem/service/query/CartItemQueryServiceTest.java
<br/>
- [#112 ]
<br/>
- 장바구니아이템 서비스 테스트 코드 구현
- 장바구니아이템 레포지토리 테스트 코드 구현
<br/>
<br/>
> 🧪 [TEST] 장바구니아이템 테스트 코드 구현

- src/main/java/com/example/cloudfour/peopleofdelivery/domain/payment/apiclient/TossApiClient.java
- src/main/java/com/example/cloudfour/peopleofdelivery/domain/payment/controller/PaymentController.java
- src/main/java/com/example/cloudfour/peopleofdelivery/domain/payment/dto/PaymentRequestDTO.java
- src/main/java/com/example/cloudfour/peopleofdelivery/domain/payment/dto/PaymentResponseDTO.java
- src/main/java/com/example/cloudfour/peopleofdelivery/domain/payment/dto/TossApproveResponse.java
- src/main/java/com/example/cloudfour/peopleofdelivery/domain/payment/dto/TossCancelResponse.java
- src/main/java/com/example/cloudfour/peopleofdelivery/domain/payment/dto/TossErrorResponse.java
- src/main/java/com/example/cloudfour/peopleofdelivery/domain/payment/dto/TossWebhookPayload.java
- src/main/java/com/example/cloudfour/peopleofdelivery/domain/payment/entity/Payment.java
- src/main/java/com/example/cloudfour/peopleofdelivery/domain/payment/enums/PaymentStatus.java
- src/main/java/com/example/cloudfour/peopleofdelivery/domain/payment/exception/PaymentErrorCode.java
- src/main/java/com/example/cloudfour/peopleofdelivery/domain/payment/exception/PaymentHistoryErrorCode.java
- src/main/java/com/example/cloudfour/peopleofdelivery/domain/payment/exception/PaymentHistoryException.java
- src/main/java/com/example/cloudfour/peopleofdelivery/domain/payment/repository/PaymentRepository.java
- src/main/java/com/example/cloudfour/peopleofdelivery/domain/payment/service/command/PaymentCommandService.java
- src/main/java/com/example/cloudfour/peopleofdelivery/domain/payment/service/command/PaymentCommandServiceImpl.java
- src/main/java/com/example/cloudfour/peopleofdelivery/domain/payment/service/query/PaymentQueryServiceImpl.java
- src/main/resources/application.yml
<br/>
- #141 
<br/>
- toss 연동 오류 수정
- delete -> cancel로 수정
<br/>
<br/>
> 🐛 [FIX] toss 연동 오류 수정

- src/test/java/com/example/cloudfour/peopleofdelivery/unit/domain/store/repository/StoreRepositoryTest.java
<br/>
- #143 
<br/>
- createMockUserWithRole -> createMockUserWithRoleAndRegion
<br/>
<br/>
> 🔨 [REFACTORY] Factory 메소드 이름 변경에 따른 StoreRepositoryTest 메소드 이름 수정

- src/main/java/com/example/cloudfour/peopleofdelivery/domain/user/controller/UserController.java
- src/main/java/com/example/cloudfour/peopleofdelivery/domain/user/dto/UserRequestDTO.java
- src/main/java/com/example/cloudfour/peopleofdelivery/domain/user/dto/UserResponseDTO.java
- src/main/java/com/example/cloudfour/peopleofdelivery/domain/user/entity/User.java
- src/main/java/com/example/cloudfour/peopleofdelivery/domain/user/entity/UserAddress.java
- src/main/java/com/example/cloudfour/peopleofdelivery/domain/user/enums/LoginType.java
- src/main/java/com/example/cloudfour/peopleofdelivery/domain/user/repository/UserRepository.java
- src/main/java/com/example/cloudfour/peopleofdelivery/domain/user/service/UserAddressService.java
- src/main/java/com/example/cloudfour/peopleofdelivery/global/auth/config/SecurityConfig.java
- src/main/java/com/example/cloudfour/peopleofdelivery/global/auth/controller/AuthController.java
- src/main/java/com/example/cloudfour/peopleofdelivery/global/auth/controller/OAuthController.java
- src/main/java/com/example/cloudfour/peopleofdelivery/global/auth/dto/AuthRequestDTO.java
- src/main/java/com/example/cloudfour/peopleofdelivery/global/auth/dto/AuthResponseDTO.java
- src/main/java/com/example/cloudfour/peopleofdelivery/global/auth/dto/OAuthRequestDTO.java
- src/main/java/com/example/cloudfour/peopleofdelivery/global/auth/entity/VerificationCode.java
- src/main/java/com/example/cloudfour/peopleofdelivery/global/auth/jwt/JwtAuthenticationFilter.java
- src/main/java/com/example/cloudfour/peopleofdelivery/global/auth/jwt/JwtTokenProvider.java
- src/main/java/com/example/cloudfour/peopleofdelivery/global/auth/oauth/CustomOAuth2UserService.java
- src/main/java/com/example/cloudfour/peopleofdelivery/global/auth/oauth/OAuth2SuccessHandler.java
- src/main/java/com/example/cloudfour/peopleofdelivery/global/auth/service/AuthService.java
- src/main/java/com/example/cloudfour/peopleofdelivery/global/auth/service/JpaUserDetailsService.java
- src/main/java/com/example/cloudfour/peopleofdelivery/global/auth/service/OAuthService.java
- src/main/java/com/example/cloudfour/peopleofdelivery/global/auth/userdetails/CustomUserDetails.java
- src/main/java/com/example/cloudfour/peopleofdelivery/global/config/RestClientConfig.java
- src/main/java/com/example/cloudfour/peopleofdelivery/global/entity/BaseEntity.java
<br/>
- #144 
<br/>
- 주석 제거
- 미사용 import 제거
- 고객, 점주 로그인 분리
<br/>
<br/>
> 🔨 [REFACTOR] user, auth 수정사항 반영

- src/main/java/com/example/cloudfour/peopleofdelivery/domain/store/service/command/StoreCommandService.java
- src/test/java/com/example/cloudfour/peopleofdelivery/fixtures/Factory.java
- src/test/java/com/example/cloudfour/peopleofdelivery/integration/IntegrationCustomerTest.java
- src/test/java/com/example/cloudfour/peopleofdelivery/integration/IntegrationOwnerTest.java
- src/test/java/com/example/cloudfour/peopleofdelivery/integration/IntegrationTest.java
- src/test/resources/application-test.yml
- src/test/resources/test-data.sql
<br/>
- #146 
<br/>
정상 시나리오
- 회원가입 및 로그인 → JWT 토큰 획득
- 음식점 조회 → 가게 목록 확인
- 메뉴 선택 → 특정 가게의 메뉴 조회
- 장바구니 생성 → 선택한 메뉴를 장바구니에 추가
- 주문 생성 → 장바구니 기반 주문 생성
- 결제 처리 → 주문에 대한 결제 시뮬레이션
- 리뷰 작성 → 주문 완료 후 리뷰 등록
- 로그아웃까지(추가 해야함)
예외 시나리오
- 잘못된 로그인 정보 처리
- 비밀번호 규칙 위반 방지
- 미인증 접근 차단
- 존재하지 않는 리소스 404 처리
- 빈 장바구니 주문 방지
- 중복 이메일 회원가입 방지
- 잘못된 요청 형식 처리
Factory.java
- PaymentStatus.PAID -> PaymentStatus.APPROVED
<br/>
<br/>
> 🧪 [TEST] 통합테스트 구현 및 Factory.java 수정
